export { Header } from './Header'
export { Footer } from './Footer'
export { Main } from './Main'
export { ModalWindow } from './ModalWindow/ModalWindow'
export { ReservationForm } from './ReservationForm'
export { HeroSection } from './HeroSection'
